#!/bin/bash

yarn workspace @internal/backstage-plugin-firelink export-dynamic
cd plugins/firelink
rm *.tgz
npm pack
cd ../..
rm *.tgz
mv plugins/visual-qontract/*.tgz .
shasum -a 256 *.tgz | awk '{print $1}' | xxd -r -p | base64